apiVersion: v2
name: konductor
description: An unofficial Helm chart for Netflix Conductor
type: application
version: 0.0.1
appVersion: "3f81d3"
home: https://github.com/project-konductor/konductor
sources:
  - https://github.com/project-konductor/konductor
keywords:
  - conductor
  - konductor
  - workflows
  - netflix
dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co
    version: 7.17.3
    condition: elasticsearch.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.13.2
    condition: redis.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.2.3
    condition: postgresql.enabled
