nameOverride: ""
fullnameOverride: ""

server:
  replicaCount: 1
  image:
    repository: quay.io/konductor/conductor
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  # Extra properties for server's config.properties file
  properties: ~

  imagePullSecrets: []
  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts: []
      # - host: conductor.example.com
      #   paths:
      #     - path: /
      #       pathType: ImplementationSpecific
    tls: []
    #  - secretName: conductor-example-tls
    #    hosts:
    #      - conductor.example.com

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

ui:
  replicaCount: 1
  image:
    repository: quay.io/konductor/conductor-ui
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []
  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts: []
      # - host: ui.conductor.example.com
      #   paths:
      #     - path: /
      #       pathType: ImplementationSpecific
    tls: []
    #  - secretName: conductor-ui-example-tls
    #    hosts:
    #      - ui.conductor.example.com

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

elasticsearch:
  enabled: true
  fullnameOverride: konductor-elasticsearch
  replicas: 1
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

redis:
  enabled: true
  fullnameOverride: konductor-redis
  architecture: standalone
  auth:
    enabled: false

postgresql:
  enabled: true
  fullnameOverride: konductor-postgresql
  auth:
    postgresPassword: conductor
    username: conductor
    password: conductor
    database: conductor

  # sysctl:
  #   enabled: true

  # volumePermissions:
  #   enabled: true

  # global:
  #   storageClass: ~ 
